### PR TITLE
Merge to update main with job submission functionality

### PR DESCRIPTION
**Pull request by adamfitzgibbon**
This merge brings in the job submission functionality:

1. clusterLandingCtrl was updated so the button changes the page to the job submission form.
2. The form is fully functional with field validation.
3. Parses form data into slurm file which is uploaded to clusters and submitted automatically.

screen shot 2015-11-16 at 12 07 02 pm

Future work to be done:

1. Pretty up the form (make the module selectize display as intended)
2. Add a back or cancel button.
3. Look into file path bug (occasionally the job couldn't find dependent files, even if an absolute path was given)
4. Find a better solution than requiring the user to specify the file paths for the job file, error, and output. (probably by using an HCCGo specific directory)

### CODE REVIEW

**Comment by djw8605** [comment]
It looks as though you committed your src/node_modules directory.  Please remove those files from the commits.  You may need to edit the commits (git rebase -i) in order to add / remove them in the same commit, so that they are effectively never in the code base.

**Comment by djw8605** [comment]
Look at this document on how to remove a directory from the history.  https://stackoverflow.com/questions/10067848/remove-folder-and-its-contents-from-git-githubs-history

**Comment by adamfitzgibbon** [comment]
Yeah, sorry, I am unable to come in on Tuesdays which is why I haven't fixed that yet. Should have it fixed tomorrow.

**Comment by adamfitzgibbon** [comment]
Alright, it looks like the node_modules directory has been completely removed from history. I'm not sure if it's intended functionality, but each commit seems to have doubled for some reason. In any case, let me know if I need to change anything else.

**Comment by djw8605** [comment]
I see a few things that are yet to be completed in the pull request summary.  Has there been any progress on that front?  We don't need to have the file transfer perfected yet, but add a back or cancel button is a must.

**Comment by adamfitzgibbon** [comment]
Yeah, the cancel button has been added, I just forgot to commit it. I still want to fiddle a bit with how the two buttons look when the page is resized but that can be saved for later.

**Comment by adamfitzgibbon** [comment]
Is there anything else that I should work on in the short term?

**Comment by djw8605** [comment]
Is it able to submit a job?  Last I remember all that was implemented was the form.

**Comment by adamfitzgibbon** [comment]
Yes, sorry if I made that unclear. The form data is parsed into a slurm file, the slurm file is uploaded to the specified location and then the job is submitted. I'm running into an issue where it sometimes can't find required files even when an absolute file name is specified but sometimes it does. But the job is for sure getting submitted.

**Pull request merged**
